[project]
name = "VideoConverter"
version = "0.1.0"
description = "Script to convert videos from one folder"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "pytest>=8.4.1",
]
